### ISSUE TITLE
Bad Request response in get-datasets

### ISSUE THREAD

**Issue by Timodie** [domoinc/domo-node-sdk#6] opened 2017-09-11 15:37 UTC
domo.datasets.get(datasetId)
	.then(res => { console.log(`\nDataset: ${res.id} - ${res.name}`); })
	.catch(console.error);

The method above seems to have a bug. I am trying to get data from domo with the right credentials.
I am able to get this data successfully in Postman by using the url:
 https://api.domo.com/v1/datasets/{DATASET_ID}/data
with the right authentication as well

However when I use the method above, I get the error which I've summarized as follows:
{
    "status": 400,
    "statusReason": "Bad Request",
    "message": "Infrastructure problem (403): Access is denied",
    "toe": "DV3ET85U1V-GQ837-V5TN9"
}
I am sure this is because in your sdk you do not concated "data" to the url i.e.
  https://api.domo.com/v1/datasets/{DATASET_ID}/
I tried it postman and got the same error the method throws.

I've tried to manually add the "/data" to the url in the sdk but it still does not work.
Thanks

**Comment by walexnelson** [comment] 2017-09-11 17:07
Thanks @Timodie, 

Sorry, the examples are incomplete (updates are coming) so you'll have to look at the [test](https://github.com/domoinc/domo-node-sdk/blob/master/test/DatasetClient.spec.ts) files to see full usage.

* `datasets.get` is to retrieve the dataset as documented [here](https://developer.domo.com/docs/dataset-api-reference/dataset#Retrieve%20a%20DataSet)
* `datasets.exportData` is to export the data from the provided dataset, as documented [here](https://developer.domo.com/docs/dataset-api-reference/dataset#Export%20data%20from%20DataSet)

Looks like you want to export the data.

That being said, I'm not able to reproduce the error you're running into with the `datasets.get`. Do you have access to the dataset you're trying to `GET` in Domo?

**Comment by Timodie** [comment] 2017-09-11 17:42
I solved the issue, but I'm also going to look at the the exportData method. 
So apparently, the json parameter in options which is passed down to the request-promise-native call should be absent or set to false when requesting data

**Comment by walexnelson** [comment] 2017-09-11 19:16
Closing this in favor of the new issue @Timodie brought up for the JSON option. See #7

**Closed by walexnelson** 2017-09-11 19:16 UTC
